# Generated by Django 4.1.4 on 2022-12-17 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('second_hand', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondhandproduct',
            name='uploaded_by',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
