# Generated by Django 4.1.4 on 2022-12-17 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='made_for',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
