# Generated by Django 4.1.4 on 2022-12-14 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='profile',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='cart_user',
        ),
        migrations.AddField(
            model_name='profile',
            name='cart',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='auth_app.cart'),
        ),
    ]
