# Generated by Django 4.1.4 on 2022-12-14 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_rename_user_profile_profile_remove_cart_cart_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth_app.cart'),
        ),
    ]
