# Generated by Django 4.1.4 on 2022-12-14 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_alter_profile_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cart',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
